import argparse
import os
from collections import namedtuple

import numpy as np
from PIL import Image, ImageDraw, ImageFont

from protocol import HEIGHT, WIDTH

DIGITS = "0123456789"
CHARS = DIGITS + ":"
GAP = 2
# Room for the anti burn-in shift the device applies to the big clock.
SHIFT_MARGIN = 4
HOST_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_FONT = os.path.join(HOST_DIR, "fonts", "Anton-Regular.ttf")
OUTPUT = os.path.join(os.path.dirname(HOST_DIR), "device", "lib", "bigfont.py")

Font = namedtuple("Font", "height glyphs")


def _render_size(font):
    boxes = {ch: font.getbbox(ch) for ch in CHARS}
    top = min(box[1] for box in boxes.values())
    height = max(box[3] for box in boxes.values()) - top
    digit_width = max(boxes[d][2] - boxes[d][0] for d in DIGITS)
    glyphs = {}
    for ch, (left, _, right, _) in boxes.items():
        width = digit_width if ch in DIGITS else right - left
        image = Image.new("L", (width, height), 0)
        ImageDraw.Draw(image).text(((width - (right - left)) // 2 - left, -top), ch, fill=255, font=font)
        bits = np.asarray(image) >= 128
        columns = np.where(bits.any(axis=0))[0]
        glyphs[ch] = (width, int(columns.min()), int(columns.max()), np.packbits(bits, axis=1).tobytes())
    return Font(height, glyphs)


def _fits(font):
    total = 4 * font.glyphs["0"][0] + font.glyphs[":"][0] + 4 * GAP
    return total <= WIDTH - SHIFT_MARGIN and font.height <= HEIGHT - SHIFT_MARGIN


def render(font_path=DEFAULT_FONT):
    for size in range(HEIGHT * 2, 7, -1):
        font = _render_size(ImageFont.truetype(font_path, size))
        if _fits(font):
            return font
    raise ValueError("no font size fits the panel")


def module_source(font):
    lines = ["# Generated by host/gen_bigfont.py, do not edit.",
             "HEIGHT = %d" % font.height,
             "GAP = %d" % GAP,
             "# char: (cell width, first ink column, last ink column, MONO_HLSB rows)",
             "GLYPHS = {"]
    for ch in CHARS:
        width, ink_left, ink_right, data = font.glyphs[ch]
        lines.append("    %r: (%d, %d, %d, %r)," % (ch, width, ink_left, ink_right, data))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate device/lib/bigfont.py for the OLED clock.")
    parser.add_argument("--font", default=DEFAULT_FONT, help="TTF/OTF path (default: vendored Anton)")
    args = parser.parse_args()
    font = render(args.font)
    with open(OUTPUT, "w", newline="\n") as out:
        out.write(module_source(font))
    print("wrote %s: height %d, digit width %d" % (OUTPUT, font.height, font.glyphs["0"][0]))


if __name__ == "__main__":
    main()
